package com.co.master.sell.domain.entities;
// Generated 1/07/2016 09:30:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private int idCiudad;
     private String descripcion;
     private Set<Provedor> provedors = new HashSet<Provedor>(0);
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public Ciudad() {
    }

	
    public Ciudad(int idCiudad, String descripcion) {
        this.idCiudad = idCiudad;
        this.descripcion = descripcion;
    }
    public Ciudad(int idCiudad, String descripcion, Set<Provedor> provedors, Set<Cliente> clientes) {
       this.idCiudad = idCiudad;
       this.descripcion = descripcion;
       this.provedors = provedors;
       this.clientes = clientes;
    }
   
    public int getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Provedor> getProvedors() {
        return this.provedors;
    }
    
    public void setProvedors(Set<Provedor> provedors) {
        this.provedors = provedors;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


