package com.co.master.sell.domain.entities;
// Generated 1/07/2016 09:30:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private ClienteId id;
     private Ciudad ciudad;
     private TiposDocumento tiposDocumento;
     private String nombres;
     private String apellidos;
     private String telefono;
     private String direccion;
     private String celular;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Cliente() {
    }

	
    public Cliente(ClienteId id, Ciudad ciudad, TiposDocumento tiposDocumento, String nombres, String apellidos) {
        this.id = id;
        this.ciudad = ciudad;
        this.tiposDocumento = tiposDocumento;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    public Cliente(ClienteId id, Ciudad ciudad, TiposDocumento tiposDocumento, String nombres, String apellidos, String telefono, String direccion, String celular, Set<Factura> facturas) {
       this.id = id;
       this.ciudad = ciudad;
       this.tiposDocumento = tiposDocumento;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.direccion = direccion;
       this.celular = celular;
       this.facturas = facturas;
    }
   
    public ClienteId getId() {
        return this.id;
    }
    
    public void setId(ClienteId id) {
        this.id = id;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public TiposDocumento getTiposDocumento() {
        return this.tiposDocumento;
    }
    
    public void setTiposDocumento(TiposDocumento tiposDocumento) {
        this.tiposDocumento = tiposDocumento;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


