package com.co.master.sell.domain.entities;
// Generated 1/07/2016 09:30:19 AM by Hibernate Tools 4.3.1



/**
 * ClienteId generated by hbm2java
 */
public class ClienteId  implements java.io.Serializable {


     private String dni;
     private int tipoDocumento;

    public ClienteId() {
    }

    public ClienteId(String dni, int tipoDocumento) {
       this.dni = dni;
       this.tipoDocumento = tipoDocumento;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public int getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(int tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClienteId) ) return false;
		 ClienteId castOther = ( ClienteId ) other; 
         
		 return ( (this.getDni()==castOther.getDni()) || ( this.getDni()!=null && castOther.getDni()!=null && this.getDni().equals(castOther.getDni()) ) )
 && (this.getTipoDocumento()==castOther.getTipoDocumento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDni() == null ? 0 : this.getDni().hashCode() );
         result = 37 * result + this.getTipoDocumento();
         return result;
   }   


}


