package com.co.master.sell.domain.entities;
// Generated 1/07/2016 09:30:19 AM by Hibernate Tools 4.3.1



/**
 * DetalleFacturaId generated by hbm2java
 */
public class DetalleFacturaId  implements java.io.Serializable {


     private String factura;
     private int articulo;

    public DetalleFacturaId() {
    }

    public DetalleFacturaId(String factura, int articulo) {
       this.factura = factura;
       this.articulo = articulo;
    }
   
    public String getFactura() {
        return this.factura;
    }
    
    public void setFactura(String factura) {
        this.factura = factura;
    }
    public int getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(int articulo) {
        this.articulo = articulo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleFacturaId) ) return false;
		 DetalleFacturaId castOther = ( DetalleFacturaId ) other; 
         
		 return ( (this.getFactura()==castOther.getFactura()) || ( this.getFactura()!=null && castOther.getFactura()!=null && this.getFactura().equals(castOther.getFactura()) ) )
 && (this.getArticulo()==castOther.getArticulo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFactura() == null ? 0 : this.getFactura().hashCode() );
         result = 37 * result + this.getArticulo();
         return result;
   }   


}


