package com.co.master.sell.domain.entities;
// Generated 1/07/2016 09:30:19 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Devolucion generated by hbm2java
 */
public class Devolucion  implements java.io.Serializable {


     private int idDevolucion;
     private DetalleFactura detalleFactura;
     private String motivo;
     private Date fechaDevolucion;
     private int cantidad;

    public Devolucion() {
    }

    public Devolucion(int idDevolucion, DetalleFactura detalleFactura, String motivo, Date fechaDevolucion, int cantidad) {
       this.idDevolucion = idDevolucion;
       this.detalleFactura = detalleFactura;
       this.motivo = motivo;
       this.fechaDevolucion = fechaDevolucion;
       this.cantidad = cantidad;
    }
   
    public int getIdDevolucion() {
        return this.idDevolucion;
    }
    
    public void setIdDevolucion(int idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public DetalleFactura getDetalleFactura() {
        return this.detalleFactura;
    }
    
    public void setDetalleFactura(DetalleFactura detalleFactura) {
        this.detalleFactura = detalleFactura;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


