package com.co.master.sell.domain.entities;
// Generated 1/07/2016 09:30:19 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private String idFactura;
     private Cliente cliente;
     private FormaPago formaPago;
     private Vendedor vendedor;
     private Date fechaVenta;
     private BigDecimal totalVenta;
     private BigDecimal iva;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Factura() {
    }

	
    public Factura(String idFactura, Cliente cliente, FormaPago formaPago, Vendedor vendedor, Date fechaVenta, BigDecimal totalVenta) {
        this.idFactura = idFactura;
        this.cliente = cliente;
        this.formaPago = formaPago;
        this.vendedor = vendedor;
        this.fechaVenta = fechaVenta;
        this.totalVenta = totalVenta;
    }
    public Factura(String idFactura, Cliente cliente, FormaPago formaPago, Vendedor vendedor, Date fechaVenta, BigDecimal totalVenta, BigDecimal iva, Set<DetalleFactura> detalleFacturas) {
       this.idFactura = idFactura;
       this.cliente = cliente;
       this.formaPago = formaPago;
       this.vendedor = vendedor;
       this.fechaVenta = fechaVenta;
       this.totalVenta = totalVenta;
       this.iva = iva;
       this.detalleFacturas = detalleFacturas;
    }
   
    public String getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(String idFactura) {
        this.idFactura = idFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public BigDecimal getTotalVenta() {
        return this.totalVenta;
    }
    
    public void setTotalVenta(BigDecimal totalVenta) {
        this.totalVenta = totalVenta;
    }
    public BigDecimal getIva() {
        return this.iva;
    }
    
    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


