package com.co.master.sell.domain.entities;
// Generated 1/07/2016 09:30:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FormaPago generated by hbm2java
 */
public class FormaPago  implements java.io.Serializable {


     private int idFormaPago;
     private String descripcion;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public FormaPago() {
    }

	
    public FormaPago(int idFormaPago, String descripcion) {
        this.idFormaPago = idFormaPago;
        this.descripcion = descripcion;
    }
    public FormaPago(int idFormaPago, String descripcion, Set<Factura> facturas) {
       this.idFormaPago = idFormaPago;
       this.descripcion = descripcion;
       this.facturas = facturas;
    }
   
    public int getIdFormaPago() {
        return this.idFormaPago;
    }
    
    public void setIdFormaPago(int idFormaPago) {
        this.idFormaPago = idFormaPago;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


