package com.co.master.sell.domain.entities;
// Generated 1/07/2016 09:30:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provedor generated by hbm2java
 */
public class Provedor  implements java.io.Serializable {


     private ProvedorId id;
     private Ciudad ciudad;
     private TiposDocumento tiposDocumento;
     private String nombreComercial;
     private String direccion;
     private String telefono;
     private String telefono2;
     private Set<Articulo> articulos = new HashSet<Articulo>(0);

    public Provedor() {
    }

	
    public Provedor(ProvedorId id, Ciudad ciudad, TiposDocumento tiposDocumento, String nombreComercial, String direccion, String telefono) {
        this.id = id;
        this.ciudad = ciudad;
        this.tiposDocumento = tiposDocumento;
        this.nombreComercial = nombreComercial;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Provedor(ProvedorId id, Ciudad ciudad, TiposDocumento tiposDocumento, String nombreComercial, String direccion, String telefono, String telefono2, Set<Articulo> articulos) {
       this.id = id;
       this.ciudad = ciudad;
       this.tiposDocumento = tiposDocumento;
       this.nombreComercial = nombreComercial;
       this.direccion = direccion;
       this.telefono = telefono;
       this.telefono2 = telefono2;
       this.articulos = articulos;
    }
   
    public ProvedorId getId() {
        return this.id;
    }
    
    public void setId(ProvedorId id) {
        this.id = id;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public TiposDocumento getTiposDocumento() {
        return this.tiposDocumento;
    }
    
    public void setTiposDocumento(TiposDocumento tiposDocumento) {
        this.tiposDocumento = tiposDocumento;
    }
    public String getNombreComercial() {
        return this.nombreComercial;
    }
    
    public void setNombreComercial(String nombreComercial) {
        this.nombreComercial = nombreComercial;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public Set<Articulo> getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set<Articulo> articulos) {
        this.articulos = articulos;
    }




}


