package com.co.master.sell.domain.entities;
// Generated 1/07/2016 09:30:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoArticulo generated by hbm2java
 */
public class TipoArticulo  implements java.io.Serializable {


     private int idTipoArticulo;
     private String descripcion;
     private Set<Articulo> articulos = new HashSet<Articulo>(0);

    public TipoArticulo() {
    }

	
    public TipoArticulo(int idTipoArticulo, String descripcion) {
        this.idTipoArticulo = idTipoArticulo;
        this.descripcion = descripcion;
    }
    public TipoArticulo(int idTipoArticulo, String descripcion, Set<Articulo> articulos) {
       this.idTipoArticulo = idTipoArticulo;
       this.descripcion = descripcion;
       this.articulos = articulos;
    }
   
    public int getIdTipoArticulo() {
        return this.idTipoArticulo;
    }
    
    public void setIdTipoArticulo(int idTipoArticulo) {
        this.idTipoArticulo = idTipoArticulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Articulo> getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set<Articulo> articulos) {
        this.articulos = articulos;
    }




}


