package com.co.master.sell.domain.entities;
// Generated 1/07/2016 09:30:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TiposDocumento generated by hbm2java
 */
public class TiposDocumento  implements java.io.Serializable {


     private int idTipoDocumento;
     private String descripcion;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Provedor> provedors = new HashSet<Provedor>(0);

    public TiposDocumento() {
    }

	
    public TiposDocumento(int idTipoDocumento, String descripcion) {
        this.idTipoDocumento = idTipoDocumento;
        this.descripcion = descripcion;
    }
    public TiposDocumento(int idTipoDocumento, String descripcion, Set<Cliente> clientes, Set<Provedor> provedors) {
       this.idTipoDocumento = idTipoDocumento;
       this.descripcion = descripcion;
       this.clientes = clientes;
       this.provedors = provedors;
    }
   
    public int getIdTipoDocumento() {
        return this.idTipoDocumento;
    }
    
    public void setIdTipoDocumento(int idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }
    public Set<Provedor> getProvedors() {
        return this.provedors;
    }
    
    public void setProvedors(Set<Provedor> provedors) {
        this.provedors = provedors;
    }




}


