package com.co.master.sell.domain.entities;
// Generated 1/07/2016 09:30:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private int codigoVendedor;
     private String dni;
     private String nombres;
     private String apellidos;
     private String celular;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Vendedor() {
    }

	
    public Vendedor(int codigoVendedor, String dni, String nombres, String apellidos, String celular) {
        this.codigoVendedor = codigoVendedor;
        this.dni = dni;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.celular = celular;
    }
    public Vendedor(int codigoVendedor, String dni, String nombres, String apellidos, String celular, Set<Factura> facturas) {
       this.codigoVendedor = codigoVendedor;
       this.dni = dni;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.celular = celular;
       this.facturas = facturas;
    }
   
    public int getCodigoVendedor() {
        return this.codigoVendedor;
    }
    
    public void setCodigoVendedor(int codigoVendedor) {
        this.codigoVendedor = codigoVendedor;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


